### ISSUE TITLE
Node 12 action deprecation warning

### ISSUE THREAD

**Issue by AAS97** [joshmgross/send-slack-message#2]
Just had an alert while running my CI :

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: joshmgross/send-slack-message

**Comment by joshmgross** [comment]
This should be fixed in `v1` and `v1.0.2` now
https://github.com/joshmgross/send-slack-message/releases/tag/v1.0.2
